/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import accesodatos.BarcosBD;
import accesodatos.SociosBD;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetosnegocio.Barco;
import objetosnegocio.Socio;

/**
 *
 * @author laura
 */
public class FrmBarcos extends javax.swing.JFrame {
    private final BarcosBD barcosBD;
    /**
     * Creates new form FrmBarcos
     */
    SociosBD socioBD;
    public FrmBarcos(JFrame padre) {
        initComponents();
        this.setTitle("Barcos");
        this.setLocationRelativeTo(null);
        barcosBD = new BarcosBD();
        txtIdBarco.setEnabled(false);
        this.cargarTabla();
        socioBD  = new SociosBD (); 
        agregarSocios();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdBarco = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNumamarre = new javax.swing.JTextField();
        txtCuota = new javax.swing.JTextField();
        cboSocio = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaBarcos = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtBarcos = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNoAmarre = new javax.swing.JLabel();
        lblCuota = new javax.swing.JLabel();
        lblSocio = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIdBarco.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        txtIdBarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBarco(evt);
            }
        });

        txtMatricula.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatricula(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtNumamarre.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        txtNumamarre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumamarre(evt);
            }
        });

        txtCuota.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        txtCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuota(evt);
            }
        });

        cboSocio.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        cboSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSocioActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblListaBarcos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "MATRICULA", "NOMBRE", "NO. AMARRE", "CUOTA", "ID SOCIO", "NOMBRE SOCIO"
            }
        ));
        tblListaBarcos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaBarcosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListaBarcos);

        btnEditar.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtBarcos.setFont(new java.awt.Font("Calibri Light", 3, 20)); // NOI18N
        txtBarcos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBarcos.setText("BARCOS");

        lblId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblId.setText("ID");

        lblMatricula.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblMatricula.setText("MATRICULA");

        lblNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblNombre.setText("NOMBRE");

        lblNoAmarre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblNoAmarre.setText("NO. AMARRE");

        lblCuota.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblCuota.setText("CUOTA");

        lblSocio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblSocio.setText("SOCIO");

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/340 (2).png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblMatricula)
                            .addGap(317, 317, 317))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(398, 398, 398))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblNoAmarre)
                                    .addGap(23, 23, 23)
                                    .addComponent(txtNumamarre))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCuota)
                                        .addComponent(lblSocio))
                                    .addGap(72, 72, 72)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cboSocio, 0, 241, Short.MAX_VALUE)
                                        .addComponent(txtCuota))))
                            .addGap(43, 43, 43)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtBarcos, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdBarco, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                    .addComponent(txtMatricula)
                                    .addComponent(txtNombre))))
                        .addGap(0, 0, 0)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(txtBarcos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdBarco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumamarre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNoAmarre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCuota))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSocio))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelar)
                        .addComponent(btnGuardar)
                        .addComponent(btnEditar)
                        .addComponent(btnEliminar))
                    .addComponent(btnMenu, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdBarco(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBarco
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdBarco

    private void txtMatricula(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatricula
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatricula

    private void txtNombre(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre

    private void txtNumamarre(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumamarre
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumamarre

    private void txtCuota(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuota
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuota

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        if(txtIdBarco.getText().isEmpty()&& !txtMatricula.getText().isEmpty()&& !txtNombre.getText().isEmpty()){
            guardar();
        }else if (!txtMatricula.getText().isEmpty() && !txtNombre.getText().isEmpty()){
            actualizar();
        }else{
            JOptionPane.showMessageDialog(this, "Debes llenar los campos", "Información", JOptionPane.ERROR_MESSAGE);
        }
        limpiar();
        cargarTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtBuscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar(txtBuscar.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editar(); 
        cargarTabla();
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cboSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSocioActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
//        if (!String.valueOf(evt.getKeyChar()).matches("^[A-Z]$")) {
//            evt.consume();
//        }
//        if (txtNombre.getText().length() >= 2) {
//            evt.consume();
//        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void tblListaBarcosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaBarcosMouseClicked
        mostrarInfo();
    }//GEN-LAST:event_tblListaBarcosMouseClicked

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Menu menu = new Menu();
        menu.show();
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
  
    private void buscar(String texto){
       
       ArrayList<Barco> barcos = barcosBD.buscar(texto);        
        DefaultTableModel modelo = (DefaultTableModel)tblListaBarcos.getModel();        
        modelo.setRowCount(0);
        for (Barco barco: barcos) {
            Object[] fila = new Object[3];
            fila[0] = barco.getIdBarco();
            fila[1] = barco.getMatricula();
            fila[2] = barco.getNombre();
            fila[3] = barco.getNumamarre();
            fila[4] = barco.getCuota();
            fila[5] = barco.getIdSocio();
            modelo.addRow(fila);
        }
    }
    private void guardar(){        
        String matricula = txtMatricula.getText();
        String nombre = txtNombre.getText();
        int noAmarre = Integer.parseInt(txtNumamarre.getText());
        float cuota = Float.parseFloat(txtCuota.getText());
        Socio socio = (Socio)cboSocio.getSelectedItem();
        
        Barco barco = new Barco(matricula, nombre, noAmarre, cuota, socio);
        barcosBD.guardar(barco);
    }
    
    private void actualizar(){
        int idBarco = Integer.parseInt(txtIdBarco.getText());
        String matricula = txtMatricula.getText();
        String nombre = txtNombre.getText();
        int noAmarre = Integer.parseInt(txtNumamarre.getText());
        float cuota = Float.parseFloat(txtCuota.getText());
        Socio socio = (Socio)cboSocio.getSelectedItem();
        
        Barco barco = new Barco(idBarco, matricula, nombre, noAmarre, cuota, socio);
        barcosBD.actualizar(barco);
    }
    
    private void mostrarInfo(){
        int indiceFila = tblListaBarcos.getSelectedRow();
        int idSocio = (Integer)tblListaBarcos.getValueAt(indiceFila, 0);
            Barco barco = barcosBD.consultar(idSocio);
            txtIdBarco.setText(String.valueOf(barco.getIdBarco()));
            txtMatricula.setText(barco.getMatricula());
            txtNombre.setText(barco.getNombre());
            String numAmarre = String.valueOf(barco.getNumamarre());
            txtNumamarre.setText(numAmarre);
            String cuota = String.valueOf(barco.getCuota());
            txtCuota.setText(cuota);
            cboSocio.setSelectedItem(barcosBD.obtenerSocio(barco.getIdSocio().getIdSocio()));
            
            txtMatricula.setEnabled(false);
            txtNombre.setEnabled(false);
            txtNumamarre.setEnabled(false);
            txtCuota.setEnabled(false);
            cboSocio.setEnabled(false);
    }
    
    private void eliminar(){
        int indiceFila = tblListaBarcos.getSelectedRow();
        if(indiceFila == -1){
            JOptionPane.showMessageDialog(this, "Debes seleccionar un barco", "Información", JOptionPane.ERROR_MESSAGE);
        }else{
            int idSocio = (Integer)tblListaBarcos.getValueAt(indiceFila, 0);
            Barco barco = barcosBD.consultar(idSocio);
            barcosBD.eliminar(idSocio);
            limpiar();
        }
        
    }
    
    private void editar(){
        int indiceFila = tblListaBarcos.getSelectedRow();
        if(indiceFila == -1){
            JOptionPane.showMessageDialog(this, "Debes seleccionar un barco", "Información", JOptionPane.ERROR_MESSAGE);
        }else{
            mostrarInfo();
            txtMatricula.setEnabled(true);
            txtNombre.setEnabled(true);
            txtNumamarre.setEnabled(true);
            txtCuota.setEnabled(true);
            cboSocio.setEnabled(true);
        }
    }
    
    private void limpiar(){
        txtIdBarco.setText("");
        txtMatricula.setText("");
        txtNombre.setText("");
        txtNumamarre.setText("");
        txtCuota.setText("");
        //cboSocio.setSelectedItem(ABORT);
    }    
    
    private void cargarTabla(){
        String textoBusqueda = "";
        ArrayList<Barco> barcos = barcosBD.consultar();        
        DefaultTableModel modelo = (DefaultTableModel)tblListaBarcos.getModel();        
        modelo.setRowCount(0);
        for (Barco barco: barcos) {
            Object[] fila = new Object[7];
            fila[0] = barco.getIdBarco();
            fila[1] = barco.getMatricula();
            fila[2] = barco.getNombre();
            fila[3] = barco.getNumamarre();
            fila[4] = barco.getCuota();
            fila[5] = barco.getIdSocio().getIdSocio();
            fila[6] = barco.getIdSocio().getNombre();
            modelo.addRow(fila);
        }
    }

    public void agregarSocios(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        ArrayList<Socio> socios = socioBD.consultar();
        for (Socio socio: socios) {
            modelo.addElement(socio);
            
        }
        cboSocio.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JComboBox<String> cboSocio;
    private javax.swing.JScrollPane jScrollPane1;
    javax.swing.JLabel lblCuota;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNoAmarre;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSocio;
    private javax.swing.JTable tblListaBarcos;
    private javax.swing.JLabel txtBarcos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCuota;
    private javax.swing.JTextField txtIdBarco;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumamarre;
    // End of variables declaration//GEN-END:variables
}
