/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import accesodatos.SociosBD;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetosnegocio.Socio;

/**
 *
 * @author laura
 */
public class FrmSocios extends javax.swing.JFrame {
    private final SociosBD sociosBD;
    /**
     * Creates new form FrmBarcos
     */
    public FrmSocios(JFrame padre) {
        initComponents();
        this.setTitle("Socios");
        this.setLocationRelativeTo(null);
        sociosBD = new SociosBD();
        jTextIdSocio.setEnabled(false);
        this.cargarTabla();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JLabel();
        txtdni = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        jTextIdSocio = new javax.swing.JTextField();
        jTextdni = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jTextBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtSocios = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtId.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        txtId.setText("ID");

        txtdni.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        txtdni.setText("DNI");

        txtNombre.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        txtNombre.setText("NOMBRE");

        jTextIdSocio.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        jTextIdSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdSocio(evt);
            }
        });

        jTextdni.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        jTextdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextdni(evt);
            }
        });

        jTextNombre.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombre(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jTextBuscar.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        jTextBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBuscar(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "DNI", "NOMBRE"
            }
        ));
        jTable1.setToolTipText("");
        jTable1.setAutoscrolls(false);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnEditar.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtSocios.setFont(new java.awt.Font("Calibri Light", 3, 20)); // NOI18N
        txtSocios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSocios.setText("SOCIOS");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/340 (2).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSocios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombre)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextIdSocio, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(jTextdni, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(txtId)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtdni))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(txtSocios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId)
                            .addComponent(jTextIdSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdni)
                            .addComponent(jTextdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(btnCancelar)
                        .addComponent(btnEditar)
                        .addComponent(btnEliminar))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextIdSocio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdSocio
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdSocio

    private void jTextdni(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextdni
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextdni

    private void jTextNombre(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombre
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombre

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(jTextIdSocio.getText().isEmpty()&& !jTextNombre.getText().isEmpty() && !jTextdni.getText().isEmpty()){
            if(jTextNombre.getText().matches("[a-zA-Z]")){
               guardar(); 
            }else{
                JOptionPane.showMessageDialog(this, "Nombre inválido", "Información", JOptionPane.ERROR_MESSAGE);
            }
            
        }else if (!jTextNombre.getText().isEmpty() && !jTextdni.getText().isEmpty()){
            if(jTextNombre.getText().matches("[a-zA-Z]")){
            actualizar();
            }else{
                JOptionPane.showMessageDialog(this, "Nombre inválido", "Información", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debes llenar los campos", "Ingormación", JOptionPane.ERROR_MESSAGE);
        }
        limpiar();
        cargarTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
        cargarTabla();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jTextBuscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBuscar
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBuscar

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar(jTextBuscar.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
        cargarTabla();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        mostrarInfo();
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu menu = new Menu();
        menu.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void buscar(String texto){
       
       ArrayList<Socio> socios = sociosBD.buscar(texto);        
        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();        
        modelo.setRowCount(0);
        for (Socio socio: socios) {
            Object[] fila = new Object[3];
            fila[0] = socio.getIdSocio();
            fila[1] = socio.getDni();
            fila[2] = socio.getNombre();
            modelo.addRow(fila);
        }
    }
    private void guardar(){
        String nombre = jTextNombre.getText();
        String dni = jTextdni.getText();
        Socio socio = new Socio(dni, nombre);
        sociosBD.guardar(socio);
    }
    private void mostrarInfo(){
        int indiceFila = jTable1.getSelectedRow();
        int idSocio = (Integer)jTable1.getValueAt(indiceFila, 0);
            Socio socio = sociosBD.consultar(idSocio);
            jTextIdSocio.setText(socio.getIdSocio()+"");
            jTextNombre.setText(socio.getNombre());
            jTextdni.setText(socio.getDni());
            jTextdni.setEnabled(false);
            jTextNombre.setEnabled(false);
    }
    private void eliminar(){
        int indiceFila = jTable1.getSelectedRow();
        if(indiceFila == -1){
            JOptionPane.showMessageDialog(this, "Debes seleccionar un socio", "Información", JOptionPane.ERROR_MESSAGE);
        }else{
            int idSocio = (Integer)jTable1.getValueAt(indiceFila, 0);
            Socio socio = sociosBD.consultar(idSocio);
            sociosBD.eliminar(idSocio);
            limpiar();
        }
        
    }
    
    private void editar(){
        int indiceFila = jTable1.getSelectedRow();
        if(indiceFila == -1){
            JOptionPane.showMessageDialog(this, "Debes seleccionar un socio", "Información", JOptionPane.ERROR_MESSAGE);
        }else{
            mostrarInfo();
            jTextdni.setEnabled(true);
            jTextNombre.setEnabled(true);
        }
    }
    
    private void limpiar(){
        jTextIdSocio.setText("");
        jTextNombre.setText("");
        jTextdni.setText("");
    }
    
    private void actualizar(){
        int idSocio = Integer.parseInt(jTextIdSocio.getText());
        String nombre = jTextNombre.getText();
        String dni = jTextdni.getText();
        Socio socio = new Socio(idSocio, dni, nombre);
        sociosBD.actualizar(socio);
    }
    
    private void cargarTabla(){
        String textoBusqueda = "";
        ArrayList<Socio> socios = sociosBD.consultar();        
        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();        
        modelo.setRowCount(0);
        for (Socio socio: socios) {
            Object[] fila = new Object[3];
            fila[0] = socio.getIdSocio();
            fila[1] = socio.getDni();
            fila[2] = socio.getNombre();
            modelo.addRow(fila);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextBuscar;
    private javax.swing.JTextField jTextIdSocio;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextdni;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtSocios;
    private javax.swing.JLabel txtdni;
    // End of variables declaration//GEN-END:variables
}
